<?php

//DENIED_UAS_AI_START_DELIMTIER//
$fphp_denied_uas_ais = [
    ".ai",
    "007ac9 crawler",
    "008",
    "2ip bot",
    "2ip.ru",
    "360spider",
    "360spider image",
    "360spider video",
    "360spider-image",
    "360spider-video",
    "5emerue",
    "5erue",
    "a patent crawler",
    "a6 indexer",
    "a6-indexer",
    "abonti",
    "aboundex",
    "academicbotrtu",
    "acapbot",
    "acoonbot",
    "acunetix security scanner",
    "acunetix web vulnerability scanner",
    "adbeat bot",
    "adbeat-bot",
    "adbeat_bot",
    "addsearchbot",
    "addthis",
    "adequat",
    "adequat systems",
    "adequat-systems",
    "adidxbot",
    "admantx",
    "adsbot google",
    "adsbot google- mobile",
    "adsbot google-mobile",
    "adscanner",
    "adstxtcrawler",
    "advbot",
    "agentic",
    "ahrefsbot",
    "ahrefssiteaudit",
    "ai article writer",
    "ai bot",
    "ai content detector",
    "ai dungeon",
    "ai search engine",
    "ai seo crawler",
    "ai training",
    "ai writer",
    "ai21 labs",
    "ai2bot",
    "ai2bot-dolma",
    "aibot",
    "aihitbot",
    "aimatrix",
    "aisearchbot",
    "aitraining",
    "alexa",
    "alexabot",
    "alexandriaorgbot",
    "alexibot",
    "alpha ai",
    "alphaai",
    "alphabot",
    "amazon bedrock",
    "amazon bot",
    "amazon comprehend",
    "amazon kendra",
    "amazon lex",
    "amazon sagemaker",
    "amazon silk",
    "amazon textract",
    "amazon-kendra",
    "amazonbot",
    "amelia",
    "amisoftware",
    "anderspinkbot",
    "anthropic",
    "anthropic ai",
    "anthropic-ai",
    "antibot",
    "anyevent",
    "anypicker",
    "anyword",
    "apercite",
    "appinsights",
    "applebot",
    "applebot extended",
    "applebot-extended",
    "aqua_products",
    "arabot",
    "archive.org_bot",
    "archivebot",
    "aria browse",
    "arquivo web crawler",
    "arquivo-web-crawler",
    "articoolo",
    "ask n read",
    "asknread.com",
    "aspiegelbot",
    "asterias",
    "atom feed robot",
    "augure",
    "auramundi",
    "automated writer",
    "awariobot",
    "awariorssbot",
    "awariosmartbot",
    "awesomecrawler",
    "b2b bot",
    "b2w",
    "backdoorbot",
    "backlinkcrawler",
    "baidu yunguance",
    "baidu-yunguance",
    "baiduspider",
    "baiduspider image",
    "baiduspider news",
    "baiduspider video",
    "baiduspider-image",
    "baiduspider-news",
    "baiduspider-video",
    "bardbot",
    "barkrowler",
    "bazqux",
    "bdcbot",
    "behloolbot",
    "betabot",
    "better uptime bot",
    "bidswitchbot",
    "biglotron",
    "bingai",
    "bingbot",
    "bingbot chat",
    "bingbot-chat",
    "bingpreview",
    "binlar",
    "birdcrawlerbot",
    "bitbot",
    "bitlybot",
    "bitsightbot",
    "black hole",
    "blackboard",
    "blekkobot",
    "blexbot",
    "blogmurabot",
    "blowfish",
    "blp_bbot",
    "bnf.fr_bot",
    "bomborabot",
    "bookmark search tool",
    "bot pge.chlooe.com",
    "bot-pge.chlooe.com",
    "bot.araturka.com",
    "botalot",
    "botify",
    "botrighthere",
    "boxcarbot",
    "brainobot",
    "brandonbot",
    "brandverity",
    "brave leo",
    "brightbot 1.0",
    "brightedge crawler",
    "btwebclient",
    "bubing",
    "bublupbot",
    "buck",
    "builtbottough",
    "bullseye",
    "bunnyslippers",
    "buzzbot",
    "bvbot",
    "bytedance",
    "bytespider",
    "caliperbot",
    "capsulechecker",
    "careerbot",
    "catboost",
    "cc crawler",
    "cc metadata scaper",
    "cc-crawler",
    "ccbot",
    "cegbfeieh",
    "centurybot",
    "changedetection",
    "chatglm",
    "chatgpt",
    "chatgpt user",
    "chatgpt-user",
    "checkmarknetwork",
    "cheesebot",
    "cherrypicker",
    "cherrypickerelite",
    "cherrypickerse",
    "chinchilla",
    "chrome lighthouse",
    "chrome-lighthouse",
    "cincraw",
    "cision",
    "cispa webcrawler",
    "citeseerxbot",
    "citoid",
    "claritybot",
    "claude",
    "claude web",
    "claude-web",
    "claudebot",
    "clearscope",
    "clickagy",
    "cliqzbot",
    "cloudflare alwaysonline",
    "cloudflare-alwaysonline",
    "coccoc",
    "coccocbot",
    "coccocbot web",
    "coccocbot-web",
    "cocolyzebot",
    "coexel",
    "cohere",
    "cohere ai",
    "cohere training data crawler",
    "cohere training-data-crawler",
    "cohere-ai",
    "cohere-aicohere-training-data-crawler",
    "cohere-training-data-crawler",
    "common crawl",
    "commoncrawl",
    "companybook crawler",
    "companybook-crawler",
    "conductor",
    "content crawler spider",
    "content harmony",
    "content king",
    "content optimizer",
    "content samurai",
    "contentatscale",
    "contentbot",
    "contentedge",
    "contextad bot",
    "contxbot",
    "convera",
    "converacrawler",
    "conversion ai",
    "cookiebot",
    "copernic",
    "copilot",
    "copyai",
    "copymatic",
    "copyrightcheck",
    "copyscape",
    "corporama",
    "cosmos",
    "cotoyogi",
    "crawler4j",
    "crawlq ai",
    "crawlspace",
    "crawlyprojectcrawler",
    "crescent",
    "crescent internet toolpak http ole control v.1.0",
    "crew ai",
    "crewai",
    "criteobot",
    "crunchbot",
    "crystalsemanticsbot",
    "curebot",
    "cutbot",
    "cxensebot",
    "cyberpatrol",
    "dall e",
    "dall-e",
    "dareboost",
    "dark visitor client",
    "dark visitor server",
    "datafeedwatch",
    "dataforseobot",
    "datagnionbot",
    "datanyze",
    "dataprovider",
    "dataprovider.com",
    "daum",
    "daumoa",
    "dcrawl",
    "deadlinkchecker",
    "deepai",
    "deepcrawl",
    "deepl",
    "deepmind",
    "deepnoc",
    "deepseek",
    "deusu",
    "df bot 1.0",
    "diffbot",
    "digg deeper",
    "digimind",
    "digincore bot",
    "discobot",
    "discordbot",
    "disqus",
    "dittospyder",
    "dnyzbot",
    "domain re animator bot",
    "domain re-animator bot",
    "domaincrawler",
    "domainstatsbot",
    "domcopbot",
    "dotbot",
    "doubao ai",
    "dow jones searchbot",
    "download ninja",
    "dragonbot",
    "drupact",
    "dubbotbot",
    "duckassistbot",
    "duckduckbot",
    "duckduckgo favicons-bot",
    "duckduckgo-favicons-bot",
    "e.ventures investment crawler",
    "easybib autocite",
    "ec2linkfinder",
    "edisterbot",
    "electricmonk",
    "elisabot",
    "ellisphere",
    "emailcollector",
    "emailsiphon",
    "emailwolf",
    "embedly",
    "epicbot",
    "eright",
    "erocrawler",
    "etaospider",
    "europarchive.org",
    "ev crawler",
    "ev-crawler",
    "evc batch",
    "evc-batch",
    "everyonesocialbot",
    "exabot",
    "experibot",
    "extlinksbot",
    "extractorpro",
    "eyeotabot",
    "ezid",
    "ezooms",
    "facebookbot",
    "facebookexternalhit",
    "facebot",
    "fairad client",
    "fast enterprise crawler",
    "fast webcrawler",
    "fast-webcrawler",
    "fedidb",
    "fedoraplanet",
    "feedbin",
    "feedbot",
    "feedburner",
    "feedfetcher google",
    "feedfetcher-google",
    "feedly",
    "feedspot",
    "feedvalidator",
    "femtosearchbot",
    "fever",
    "finditanswersbot",
    "findlink",
    "findthatfile",
    "findxbot",
    "firecrawl",
    "flaming attackbot",
    "flamingo_searchengine",
    "flipboardproxy",
    "fluffy",
    "flyriver",
    "foobot",
    "fr crawler",
    "fr-crawler",
    "frase ai",
    "freewebmonitoring sitechecker",
    "freshpingbot",
    "freshrss",
    "friendica",
    "friendlycrawler",
    "fuelbot",
    "fyrebot",
    "g00g1e.net",
    "g2 web services",
    "g2reader bot",
    "g2reader-bot",
    "gaisbot",
    "garlikcrawler",
    "gemini",
    "gemma",
    "genai",
    "genieo",
    "genomecrawlerd",
    "getright",
    "gigablast",
    "gigabot",
    "gingercrawler",
    "gluten free crawler",
    "gnam gnam spider",
    "gnowitnewsbot",
    "google adwords-instant",
    "google bard ai",
    "google certificates-bridge",
    "google cloudvertexbot",
    "google extended",
    "google favicon",
    "google inspectiontool",
    "google physicalweb",
    "google read-aloud",
    "google safety",
    "google site-verification",
    "google structured-data-testing-tool",
    "google web preview",
    "google xrawler",
    "google-adwords-instant",
    "google-certificates-bridge",
    "google-cloudvertexbot",
    "google-extended",
    "google-inspectiontool",
    "google-physicalweb",
    "google-read-aloud",
    "google-safety",
    "google-site-verification",
    "google-structured-data-testing-tool",
    "google-xrawler",
    "googlebot",
    "googlebot image",
    "googlebot mobile",
    "googlebot news",
    "googlebot video",
    "googlebot-image",
    "googlebot-mobile",
    "googlebot-news",
    "googlebot-video",
    "googleother",
    "googleother image",
    "googleother video",
    "googleother-image",
    "googleother-video",
    "goose",
    "gowikibot",
    "gpt",
    "gptbot",
    "grammarly",
    "grapeshot",
    "grapeshotcrawler",
    "grendizer",
    "grobbot",
    "grok",
    "grouphigh",
    "grub client",
    "grub-client",
    "grub.org",
    "gsa crawler",
    "gsa-crawler",
    "gslfbot",
    "gt bot",
    "gtbot",
    "gwene",
    "haosouspider",
    "harvest",
    "hatena",
    "hawaiibot",
    "headlesschrome",
    "hemingway editor",
    "heritrix",
    "httrack",
    "httrack 3.0",
    "hubspot",
    "hugging face",
    "humanlinks",
    "hypestat",
    "hypotenuse ai",
    "hyscore.io",
    "ia_archiver",
    "ia_archiver web.archive.org",
    "ia_archiver-web.archive.org",
    "ias crawler",
    "iaskspider",
    "iaskspider/2.0",
    "icbot",
    "icc crawler",
    "icc-crawler",
    "ichiro",
    "iframely",
    "imagesiftbot",
    "img2dataset",
    "imrbot",
    "indeedbot",
    "inetdex bot",
    "inetdex-bot",
    "inferkit",
    "infonavirobot",
    "infoobot",
    "infoseek",
    "ink editor",
    "inkforall",
    "inoreader",
    "integromedb",
    "intelium_bot",
    "intelliseek",
    "interfaxscanbot",
    "internet structure research project bot",
    "internet-structure-research-project-bot",
    "ioncrawl",
    "ip web-crawler.com",
    "ip-web-crawler.com",
    "irlbot",
    "iron33",
    "iskanie",
    "israbot",
    "isscyberriskcrawler",
    "istellabot",
    "it2media domain-crawler",
    "it2media-domain-crawler",
    "james bot",
    "jamesbot",
    "jamie's spider",
    "jasperai",
    "jenkersbot",
    "jennybot",
    "jetbot",
    "jetty",
    "jikespider",
    "jobboersebot",
    "jooblebot",
    "jpg newsbot",
    "jpg-newsbot",
    "jugendschutzprogramm crawler",
    "jugendschutzprogramm-crawler",
    "jyxobot",
    "k2spider",
    "k7mlwcbot",
    "kafkai",
    "kangaroo",
    "kangaroo bot",
    "kbcrawl",
    "kemvibot",
    "kenjin spider",
    "keys so-bot",
    "keys-so-bot",
    "keyword density",
    "keyword density ai",
    "knowings",
    "komobot",
    "komodiabot",
    "kosmiobot",
    "kstandbot",
    "landau media-spider",
    "landau-media-spider",
    "larbin",
    "laserlikebot",
    "lb spider",
    "lb-spider",
    "leadbox",
    "leikibot",
    "lexibot",
    "libweb",
    "lightspeedsystemscrawler",
    "linespider",
    "linguee",
    "linguee bot",
    "linkapediabot",
    "linkarchiver",
    "linkcheck by siteimprove.com",
    "linkdex",
    "linkdexbot",
    "linkedinbot",
    "linkextractorpro",
    "linkfluence",
    "linkisbot",
    "linko",
    "linkpadbot",
    "linkscan",
    "linkwalker",
    "lipperhey",
    "livelapbot",
    "lkxscan",
    "llama",
    "lnspiderguy",
    "lssbot",
    "lssrocketcrawler",
    "ltx71",
    "luminator robots",
    "luminator-robots",
    "lwp trivial",
    "lwp-trivial",
    "macocu",
    "magpie crawler",
    "magpie-crawler",
    "mail.ru_bot",
    "mappydata",
    "marketmuse",
    "mastodon",
    "mata hari",
    "mauibot",
    "mbcrawler",
    "mediapartners google",
    "mediapartners-google",
    "mediatoolkitbot",
    "megaindex",
    "megaindex.ru",
    "meltawer",
    "meltwater",
    "meltwaternews",
    "memorybot",
    "mention",
    "meta ai",
    "meta external",
    "meta externalagent",
    "meta externalfetcher",
    "meta-ai",
    "meta-external",
    "meta-externalagent",
    "meta-externalfetcher",
    "metaai",
    "metainspector",
    "metajobbot",
    "metatagbot",
    "metauri",
    "miixpc",
    "mindupbot",
    "minicrawler",
    "miniflux",
    "mister pix",
    "mistral",
    "mixnodecache",
    "mj12bot",
    "mlbot",
    "moatbot",
    "moget",
    "mojeek",
    "mojeekbot",
    "moodlebot",
    "moreover",
    "ms search 4.0 robot",
    "ms search 6.0 robot",
    "msiecrawler",
    "msnbot",
    "msnbot media",
    "msnbot-media",
    "msrbot",
    "mtrobot",
    "muckrack",
    "multiviewbot",
    "mytwip",
    "narrative",
    "naver blog rssbot",
    "naverbot",
    "neevabot",
    "nerdbynature.bot",
    "nerdybot",
    "netants",
    "netcraftsurveyagent",
    "netestate ne crawler",
    "neticle crawler",
    "netmechanic",
    "netresearchserver",
    "netsystemsresearch",
    "netvibes",
    "neural text",
    "neuralseo",
    "newsblur",
    "newsharecounts",
    "newsnow",
    "newspaper",
    "newzbin",
    "nextcloud",
    "nextgensearchbot",
    "nicecrawler",
    "nicerspro",
    "niki bot",
    "niki-bot",
    "nimblecrawler",
    "nimbostratus",
    "nimbostratus bot",
    "nimbostratus-bot",
    "ninja bot",
    "nixstatsbot",
    "nlux_iaharvester",
    "nmap scripting engine",
    "novaact",
    "npbot",
    "ntentbot",
    "nutch",
    "nuzzel",
    "oai searchbot",
    "oai-searchbot",
    "odklbot",
    "officestorebot",
    "offline explorer",
    "omgili",
    "omgilibot",
    "onalyticabot",
    "online webceo-bot",
    "online-webceo-bot",
    "open ai",
    "openai",
    "openbot",
    "openfind",
    "openfind data gatherer",
    "opengraphcheck",
    "openhosebot",
    "openindexspider",
    "opentext ai",
    "operator",
    "opinion tracker",
    "opinion-tracker",
    "oracle ultra search",
    "orangebot",
    "orthogaffe",
    "outbrain",
    "outclicksbot",
    "outwrite",
    "page analyzer ai",
    "page2rss",
    "pagepeeker",
    "pagething",
    "pandalytics",
    "pangubot",
    "panscient.com",
    "paperlibot",
    "paraphraser.io",
    "peer39_crawler",
    "perman",
    "perplexity ai",
    "perplexity-ai",
    "perplexity-user",
    "perplexitybot",
    "petalbot",
    "phindbot",
    "pingdom",
    "pinterest",
    "pinterestbot",
    "piplbot",
    "pocketparser",
    "postrank",
    "pr cy.ru",
    "pr-cy.ru",
    "primalbot",
    "privacyawarebot",
    "propowerbot",
    "prowebwalker",
    "prowritingaid",
    "proxem",
    "proximic",
    "psbot",
    "pubmatic crawler bot",
    "pulsepoint",
    "purebot",
    "queryn metasearch",
    "quillbot",
    "qwam content intelligence",
    "qwantbot",
    "qwantify",
    "radiation retriever 1.1",
    "rankactivelinkbot",
    "rankflex",
    "redditbot",
    "refindbot",
    "regionstuttgartbot",
    "repomonkey",
    "repomonkey bait & tackle",
    "retrevopageanalyzer",
    "reverseengineeringbot",
    "ridderbot",
    "riddler",
    "rivva",
    "robotspider",
    "robozilla",
    "rogerbot",
    "rssbot",
    "rssingbot",
    "rukicrawler",
    "ruxitsynthetic",
    "rytebot",
    "rytr",
    "safednsbot",
    "safesearch microdata crawler",
    "saplingai",
    "sbl bot",
    "sbl-bot",
    "scalenut",
    "scoop.it",
    "score3",
    "scoutjet",
    "scraper",
    "scrapy",
    "screaming frog seo spider",
    "scribdbot",
    "scriptbook",
    "scrubby",
    "search.marginalia.nu",
    "searchatlas",
    "searchmetricsbot",
    "searchpreview",
    "seekbot",
    "seekport",
    "seekport crawler",
    "seekportbot",
    "seekr",
    "seewithkids",
    "semanticbot",
    "semanticscholarbot",
    "sempi.tech",
    "semrushbot",
    "semrushbot ba",
    "semrushbot bm",
    "semrushbot coub",
    "semrushbot ct",
    "semrushbot sa",
    "semrushbot si",
    "semrushbot swa",
    "semrushbot-ba",
    "semrushbot-bm",
    "semrushbot-coub",
    "semrushbot-ct",
    "semrushbot-ocob",
    "semrushbot-sa",
    "semrushbot-si",
    "semrushbot-swa",
    "sentibot",
    "senutobot",
    "seo content machine",
    "seo robot",
    "seobilitybot",
    "seokicks",
    "seokicks robot",
    "seokicks-robot",
    "seolizer",
    "seoscanners",
    "seostar.co",
    "seostats",
    "serendeputybot",
    "serpstatbot",
    "seznambot",
    "sidetrade",
    "sidetrade indexer bot",
    "simplecrawler",
    "simplepie",
    "simplescraper",
    "simplified ai",
    "sindup",
    "sistrix crawler",
    "siteauditbot",
    "sitebot",
    "sitecheck.internetseer.com",
    "sitecheckerbotcrawler",
    "siteexplorer.info",
    "siteimprove",
    "siteimprove.com",
    "sitesnagger",
    "sitesucker",
    "skydancer",
    "skypeuripreview",
    "slack imgproxy",
    "slack-imgproxy",
    "slackbot",
    "slackbot linkexpanding",
    "slackbot-linkexpanding",
    "slickwrite",
    "slurp",
    "smtbot",
    "snap url preview service",
    "snapchat",
    "socialrankiobot",
    "sogou",
    "sogou inst spider",
    "sogou spider2",
    "sogou web spider",
    "sonic",
    "sosospider",
    "spankbot",
    "spanner",
    "spbot",
    "spin rewriter",
    "spinbot",
    "spinn3r",
    "splitsignalbot",
    "spotter",
    "sputnikbot",
    "sqlmap",
    "stability",
    "stablediffusionbot",
    "startmebot",
    "storebot google",
    "storebot-google",
    "storygizebot",
    "stractbot",
    "streamline3bot",
    "sudowrite",
    "summalybot",
    "summify",
    "superbot",
    "superfeedr",
    "surdotlybot",
    "surfer ai",
    "surveybot",
    "suzuran",
    "swiftbot",
    "swimgbot",
    "synapse",
    "synthesio",
    "sysomos",
    "szukacz",
    "t3versionsbot",
    "taboolabot",
    "tagoobot",
    "talkwater",
    "tangibleebot",
    "telegrambot",
    "teleport",
    "teleportpro",
    "telesoft",
    "teoma",
    "text blaze",
    "textcortex",
    "the intraformant",
    "the knowledge ai",
    "thenomad",
    "theoldreader.com",
    "thinklab",
    "tigerbot",
    "timpibot",
    "tineye",
    "tineye bot",
    "tineye-bot",
    "tiny tiny rss",
    "titan",
    "tocrawl",
    "tombapublicwebcrawler",
    "toplistbot",
    "toutiaospider",
    "traackr",
    "traackr.com",
    "tracemyfile",
    "trafilatura",
    "trendeo",
    "trendictionbot",
    "trendkite akashic-crawler",
    "trendkite-akashic-crawler",
    "trendsmapresolver",
    "trendybuzz",
    "trovitbot",
    "true_robot",
    "truliabot",
    "turingos",
    "turnitin",
    "turnitinbot",
    "tweetedtimes",
    "tweetmemebot",
    "twengabot",
    "twingly",
    "twitterbot",
    "twurly",
    "ubicrawler",
    "um ic",
    "um ln",
    "um-ic",
    "um-ln",
    "updownerbot",
    "upflow",
    "uptime kuma",
    "uptime-kuma",
    "uptimebot.org",
    "uptimerobot",
    "url control",
    "url_spider_pro",
    "urlappendbot",
    "urly warning",
    "usasearch",
    "usinenouvellecrawler",
    "ut dorkbot",
    "ut-dorkbot",
    "validator.nu",
    "vci",
    "vci webviewer vci webviewer win32",
    "vebidoobot",
    "vecteurplus",
    "velenpublicwebcrawler",
    "veoozbot",
    "verticalsearch",
    "viber",
    "vidnami ai",
    "vigil",
    "virustotal",
    "vkrobot",
    "vkshare",
    "voilabot",
    "voltron",
    "voluumdsp content-bot",
    "voluumdsp-content-bot",
    "vsw",
    "vuhuvbot",
    "w3c checklink",
    "w3c mobileok",
    "w3c-checklink",
    "w3c-mobileok",
    "w3c_css_validator",
    "w3c_i18n checker",
    "w3c_i18n-checker",
    "w3c_unicorn",
    "w3c_validator",
    "wasalive bot",
    "wasalive-bot",
    "wbsearchbot",
    "web archive-net.com.bot",
    "web image collector",
    "web-archive-net.com.bot",
    "webauto",
    "webbandit",
    "webcapture 2.0",
    "webcompanycrawler",
    "webcopier",
    "webcopier v.2.2",
    "webcopier v3.2a",
    "webdatastats",
    "webenhancer",
    "webmasterworldforumbot",
    "webmon",
    "webreaper",
    "websauger",
    "website quester",
    "webstripper",
    "webtechbot",
    "webzio",
    "webzio extended",
    "webzio-extended",
    "webzip",
    "wellknownbot",
    "whatcms",
    "whatsapp",
    "whisper",
    "winello",
    "winhttrack",
    "wiseguys robot",
    "wocbot",
    "woobot",
    "woorankreview",
    "wordai",
    "wordtune",
    "wordupinfosearch",
    "woriobot",
    "wormsgtp",
    "wotbox",
    "wpbot",
    "writecream",
    "writerzen",
    "writescope",
    "writesonic",
    "www collector-e",
    "www mechanize",
    "www-collector-e",
    "www-mechanize",
    "www.uptime.com",
    "xai",
    "xbot",
    "xenu",
    "xenu link sleuth",
    "xenu's",
    "xenu's link sleuth 1.1c",
    "xovibot",
    "yacybot",
    "yahoo link preview",
    "yahoo pipes 1.0",
    "yahoo! slurp",
    "yahoo slurp",
    "yahoo-slurp",
    "yak",
    "yandex",
    "yandexbot",
    "yandeximages",
    "yandexmobilebot",
    "yandexrenderresourcesbot",
    "yandexvideo",
    "yanga",
    "yellowbrandprotectionbot",
    "yeti",
    "yisouspider",
    "yoozbot",
    "youbot",
    "youdaobot",
    "youmag",
    "zabbix",
    "zao",
    "zealbot",
    "zenback bot",
    "zero gtp",
    "zerochat",
    "zeus",
    "zeus link scout",
    "zgrab",
    "zimm",
    "zite",
    "zoombot",
    "zoominfobot",
    "zumbot",
    "zuperlistbot",
    "zyborg"
];
//DENIED_UAS_AI_END_DELIMTIER//

//DENIED_UAS_OTHERS_START_DELIMTIER//
$fphp_denied_uas_others = [];
//DENIED_UAS_OTHERS_END_DELIMTIER//