CREATE TABLE authors (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
    email NVARCHAR(255) UNIQUE,
    age INT DEFAULT 18,
    nickname NVARCHAR(255) DEFAULT "Anonymous",
    updated_at TIMESTAMP DEFAULT NOW(),
);