<?php

/**
 * -----------------
 * FUNKPHP OPERATORS
 * -----------------
 * DO NOT MANUALLY EDIT THIS FILE.
 * If you are currently editing this file to see if FunkCLI will "self-heal",
 * it won't. This is a micro-framework, not your therapist. If you alter this
 * source of truth, your app will most likely crash, and your peer will know
 * you do not understand how caching and/or compiled files work.
 **/
return [
    'all' => [
        '+',
        '-',
        '*',
        '/',
        '%',
        '&',
        '|',
        '^',
        '=',
        '!=',
        '<>',
        '>',
        '>=',
        '<',
        '<=',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '&=',
        '^-=',
        '|*=',
        'ALL',
        'AND',
        'ANY',
        'BETWEEN',
        'EXISTS',
        'IN',
        'LIKE',
        'NOT',
        'OR',
        'SOME',
    ],
    'all_except_worded' => [
        '+',
        '-',
        '*',
        '/',
        '%',
        '&',
        '|',
        '^',
        '=',
        '!=',
        '<>',
        '>',
        '>=',
        '<',
        '<=',
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '&=',
        '^-=',
        '|*=',
    ],

    'arithmetic' => [
        '+',
        '-',
        '*',
        '/',
        '%',
    ],
    'bitwise' => [
        '&',
        '|',
        '^',
    ],
    'comparison' => [
        '=',
        '!=',
        '<>',
        '>',
        '>=',
        '<',
        '<=',
    ],
    'compound' => [
        '+=',
        '-=',
        '*=',
        '/=',
        '%=',
        '&=',
        '^-=',
        '|*=',
    ],
    'logical' => [
        'ALL',
        'AND',
        'ANY',
        'BETWEEN',
        'EXISTS',
        'IN',
        'LIKE',
        'NOT',
        'OR',
        'SOME',
    ],
];
