#!/usr/bin/env php
<?php // Include all CLI Functions needed to manage FunkPHP CLI!
include __DIR__ . '/funkphp/_internals/functions/cli_funs.php';

// Valid commands with valid sub-commands
// Inspiration from Trie & Hashmaps!
$validArg1withArg2Values =  [
    'help' => [],
    'compile' => ['all_routes', 'only_route', 'only_data', 'only_page', 'help'],
    'add' => ['all_routes', 'only_route', 'only_data_route', 'only_page_route', 'help'],
    'change' => ['route', 'data', 'page',  'help'],
    'delete' => [
        'route_compiled_and_singles',
        'all_backups_compiled_and_single_files_i_know_files_will_be_hard_to_get_back',
        'all_backups_finals_files_i_know_files_will_be_hard_to_get_back',
        'all_all_backups_files_i_know_files_will_be_hard_to_get_back_and_i_will_cry',
        'help',
    ],
    'restore' => [
        'route_compiled_and_singles',
        'data_compiled_and_singles',
        'page_compiled_and_singles',
        'help'
    ],
];
echo "Tset";

// No command
if (!isset($argv[1])) {
    cli_err_syntax("No FunkPHP Command was given?!\nShould be at least two arguments!");
}
// Non-existing command
if (!array_key_exists($argv[1], $validArg1withArg2Values)) {
    cli_err_syntax("That FunkCLI Command doesn't exist!");
    exit;
}
// No sub-command
if ($argv[1] !== "help" && !in_array($argv[2] ?? "", $validArg1withArg2Values[$argv[1]])) {
    cli_err_syntax("FunkCLI Command exist, but not that sub-command!");
    exit;
}

// All available dirs to use for the CLI
$outPutDir = __DIR__ . '/funkphp/_internals/compiled/';
$dirs = [
    "compiled" => __DIR__ . '/funkphp/_internals/compiled/',
    "routes" => __DIR__ . '/funkphp/routes/',
    "data" => __DIR__ . '/funkphp/data/',
    "pages" => __DIR__ . '/funkphp/pages/',
    "middlewares" => __DIR__ . '/funkphp/middlewares/',
    "middlewares_routes" => __DIR__ . '/funkphp/middlewares/R/',
    "middlewares_data" => __DIR__ . '/funkphp/middlewares/D/',
    "middlewares_pages" => __DIR__ . '/funkphp/middlewares/P/',
    "backups_finals" => __DIR__ . '/funkphp/_BACKUPS/_FINAL_BACKUPS/',
    "backups_compiled" => __DIR__ . '/funkphp/_BACKUPS/compiled/',
    "backups_routes" => __DIR__ . '/funkphp/_BACKUPS/routes/',
    "backups_data" => __DIR__ . '/funkphp/_BACKUPS/data/',
    "backups_pages" => __DIR__ . '/funkphp/_BACKUPS/pages/',
    "backups_routes_mw" => __DIR__ . '/funkphp/_BACKUPS/routes/MW/',
    "backups_data_mw" => __DIR__ . '/funkphp/_BACKUPS/data/MW/',
    "backups_pages_mw" => __DIR__ . '/funkphp/_BACKUPS/pages/MW/',
];

// Exact file paths to use for the CLI
$exactFiles = [
    "troute_data" => $dirs['compiled'] . "troute_data.php",
    "troute_page" => $dirs['compiled'] . "troute_page.php",
    "troute_route" => $dirs['compiled'] . "troute_route.php",
    "single_routes" => $dirs['routes'] . "route_single_routes.php",
    "single_middlewares" => $dirs['routes'] . "route_middleware_routes.php",
    "single_data" => $dirs['data'] . "data_single_routes.php",
    "single_middlewares_data" => $dirs['data'] . "data_middleware_routes.php",
    "single_page" => $dirs['pages'] . "page_single_routes.php",
    "single_middlewares_page" => $dirs['pages'] . "page_middleware_routes.php",
];

// Load current routes, data and pages before processing any commands
$singleRoutesRoute = include __DIR__ . '/funkphp/routes/route_single_routes.php';
$singleRoutesData = include __DIR__ . '/funkphp/data/data_single_routes.php';
$singleRoutesPage = include __DIR__ . '/funkphp/pages/page_single_routes.php';
$middlewareRoutesRoute = include  __DIR__ . '/funkphp/routes/route_middleware_routes.php';
$middlewareRoutesData = include __DIR__ . '/funkphp/data/data_middleware_routes.php';
$middlewareRoutesPage = include __DIR__ . '/funkphp/pages/page_middleware_routes.php';

// Compile only based on user input
// Compile all routes
// Define the command actions map
$commands = [
    'compile' => [
        'all_routes' => function () use (
            $singleRoutesRoute,
            $middlewareRoutesRoute,
            $singleRoutesPage,
            $middlewareRoutesPage,
            $singleRoutesData,
            $middlewareRoutesData,
            $exactFiles,
            $dirs
        ) {
            // Backup the old route files first

            // Backup paths
            $backupFinalsPath = $dirs['backups_finals'];
            $backupCompiledPath = $dirs['backups_compiled'];
            $backupRouteRoutePath = $dirs['backups_routes'];
            $backupDataRoutePath = $dirs['backups_data'];
            $backupPageRoutePath = $dirs['backups_pages'];

            // Routes
            $oldTrouteRouteFile = $exactFiles['troute_route'];
            $oldSingleRouteRouteFile = $exactFiles['single_routes'];
            $oldSingleMiddlwaresRouteFile = $exactFiles['single_middlewares'];

            // Data
            $oldTrouteDataFile = $exactFiles['troute_data'];
            $oldSingleDataFile = $exactFiles['single_data'];
            $oldSingleMiddlwaresDataFile = $exactFiles['single_middlewares_data'];

            // Pages
            $oldTroutePageFile = $exactFiles['troute_page'];
            $oldSinglePageFile = $exactFiles['single_page'];
            $oldSingleMiddlwaresPageFile = $exactFiles['single_middlewares_page'];

            // Now backup the old route files

            // Routes
            cli_backup_file_until_success($backupCompiledPath . "troute_route", ".php", $oldTrouteRouteFile);
            cli_backup_file_until_success($backupFinalsPath . "troute_route", ".php", $oldTrouteRouteFile);
            cli_backup_file_until_success($backupRouteRoutePath . "route_single_routes", ".php", $oldSingleRouteRouteFile);
            cli_backup_file_until_success($backupRouteRoutePath . "route_single_middlwares", ".php", $oldSingleMiddlwaresRouteFile);
            cli_backup_file_until_success($backupFinalsPath . "route_single_routes", ".php", $oldSingleRouteRouteFile);
            cli_backup_file_until_success($backupFinalsPath . "route_single_middlwares", ".php", $oldSingleMiddlwaresRouteFile);

            // Data
            cli_backup_file_until_success($backupCompiledPath . "troute_data", ".php", $oldTrouteDataFile);
            cli_backup_file_until_success($backupFinalsPath . "troute_data", ".php", $oldTrouteDataFile);
            cli_backup_file_until_success($backupDataRoutePath . "data_single_routes", ".php", $oldSingleDataFile);
            cli_backup_file_until_success($backupDataRoutePath . "data_single_middlwares", ".php", $oldSingleMiddlwaresDataFile);
            cli_backup_file_until_success($backupFinalsPath . "data_single_routes", ".php", $oldSingleDataFile);
            cli_backup_file_until_success($backupFinalsPath . "data_single_middlwares", ".php", $oldSingleMiddlwaresDataFile);

            // Pages
            cli_backup_file_until_success($backupCompiledPath . "troute_page", ".php", $oldTroutePageFile);
            cli_backup_file_until_success($backupFinalsPath . "troute_page", ".php", $oldTroutePageFile);
            cli_backup_file_until_success($backupPageRoutePath . "page_single_routes", ".php", $oldSinglePageFile);
            cli_backup_file_until_success($backupPageRoutePath . "page_single_middlwares", ".php", $oldSingleMiddlwaresPageFile);
            cli_backup_file_until_success($backupFinalsPath . "page_single_routes", ".php", $oldSinglePageFile);
            cli_backup_file_until_success($backupFinalsPath . "page_single_middlwares", ".php", $oldSingleMiddlwaresPageFile);

            // Then build and output new route files
            $compiledRouteRoutes = cli_build_compiled_routes($singleRoutesRoute['ROUTES'], $middlewareRoutesRoute['MIDDLEWARES']);
            $compiledPageRoutes = cli_build_compiled_routes($singleRoutesPage['ROUTES'], $middlewareRoutesPage['MIDDLEWARES']);
            $compiledDataRoutes = cli_build_compiled_routes($singleRoutesData['ROUTES'], $middlewareRoutesData['MIDDLEWARES']);
            cli_output_compiled_routes($compiledRouteRoutes, "troute_route");
            cli_output_compiled_routes($compiledPageRoutes, "troute_page");
            cli_output_compiled_routes($compiledDataRoutes, "troute_data");
            cli_success("All routes compiled successfully!");
        },
        'only_route' => function () use ($singleRoutesRoute, $middlewareRoutesRoute, $exactFiles, $dirs) {
            // Backup the old route file first (troute and single_routes)
            $oldRouteFile = $exactFiles['troute_route'];
            $oldSingleRouteFile = $exactFiles['single_routes'];
            $oldSingleRouteMiddlewareFile = $exactFiles['single_middlewares'];
            $backupRoutePath = $dirs['backups_routes'];
            $backupCompiledPath = $dirs['backups_compiled'];
            $backupFinalsPath = $dirs['backups_finals'];
            cli_backup_file_until_success($backupCompiledPath . "troute_route", ".php", $oldRouteFile);
            cli_backup_file_until_success($backupFinalsPath . "troute_route", ".php", $oldRouteFile);
            cli_backup_file_until_success($backupRoutePath . "route_single_routes", ".php", $oldSingleRouteFile);
            cli_backup_file_until_success($backupFinalsPath . "route_single_routes", ".php", $oldSingleRouteFile);
            cli_backup_file_until_success($backupRoutePath . "route_middleware_routes", ".php", $oldSingleRouteMiddlewareFile);
            cli_backup_file_until_success($backupFinalsPath . "route_middleware_routes", ".php", $oldSingleRouteMiddlewareFile);

            // Then build and output new route file
            $compiledRouteRoutes = cli_build_compiled_routes($singleRoutesRoute['ROUTES'], $middlewareRoutesRoute['MIDDLEWARES']);
            cli_output_compiled_routes($compiledRouteRoutes, "troute_route");
            cli_success("Compiled Only Route routes!");
        },
        'only_data' => function () use ($singleRoutesData, $middlewareRoutesData, $exactFiles, $dirs) {
            // Backup the old route file first
            $oldRouteFile = $exactFiles['troute_data'];
            $oldSingleRouteFile = $exactFiles['single_data'];
            $oldSingleRouteMiddlewareFile = $exactFiles['single_middlewares_data'];
            $backupRoutePath = $dirs['backups_data'];
            $backupCompiledPath = $dirs['backups_compiled'];
            $backupFinalsPath = $dirs['backups_finals'];
            cli_backup_file_until_success($backupCompiledPath . "troute_data", ".php", $oldRouteFile);
            cli_backup_file_until_success($backupFinalsPath . "troute_data", ".php", $oldRouteFile);
            cli_backup_file_until_success($backupRoutePath . "data_single_routes", ".php", $oldSingleRouteFile);
            cli_backup_file_until_success($backupFinalsPath . "data_single_routes", ".php", $oldSingleRouteFile);
            cli_backup_file_until_success($backupRoutePath . "data_middleware_routes", ".php", $oldSingleRouteMiddlewareFile);
            cli_backup_file_until_success($backupFinalsPath . "data_middleware_routes", ".php", $oldSingleRouteMiddlewareFile);

            // Then build and output new route file
            $compiledDataRoutes = cli_build_compiled_routes($singleRoutesData['ROUTES'], $middlewareRoutesData['MIDDLEWARES']);
            cli_output_compiled_routes($compiledDataRoutes, "troute_data");
            cli_success("Compiled Only Data routes!");
        },
        'only_page' => function () use ($singleRoutesPage, $middlewareRoutesPage, $exactFiles, $dirs) {
            // Backup the old route file first
            $oldRouteFile = $exactFiles['troute_page'];
            $oldSingleRouteFile = $exactFiles['single_page'];
            $oldSingleRouteMiddlewareFile = $exactFiles['single_middlewares_page'];
            $backupRoutePath = $dirs['backups_pages'];
            $backupCompiledPath = $dirs['backups_compiled'];
            $backupFinalsPath = $dirs['backups_finals'];
            cli_backup_file_until_success($backupCompiledPath . "troute_page", ".php", $oldRouteFile);
            cli_backup_file_until_success($backupFinalsPath . "troute_page", ".php", $oldRouteFile);
            cli_backup_file_until_success($backupRoutePath . "page_single_routes", ".php", $oldSingleRouteFile);
            cli_backup_file_until_success($backupFinalsPath . "page_single_routes", ".php", $oldSingleRouteFile);
            cli_backup_file_until_success($backupRoutePath . "page_middleware_routes", ".php", $oldSingleRouteMiddlewareFile);
            cli_backup_file_until_success($backupFinalsPath . "page_middleware_routes", ".php", $oldSingleRouteMiddlewareFile);


            // Then build and output new route file
            $compiledPageRoutes = cli_build_compiled_routes($singleRoutesPage['ROUTES'], $middlewareRoutesPage['MIDDLEWARES']);
            cli_output_compiled_routes($compiledPageRoutes, "troute_page");
            cli_success("Compiled Only Page routes!");
        },
        'help' => function () {
            cli_info_multiline("FunkCLI - Compile Help");
            cli_info_multiline("Usage: funkcli compile [all_routes|only_[route|page|data]]");
            cli_info_multiline("The different values:");
            cli_info_multiline("  all_routes - Compiles all routes");
            cli_info_multiline("  only_route - Compiles only route routes");
            cli_info_multiline("  only_page - Compiles only page routes");
            cli_info_multiline("  only_data - Compiles only data routes");
            cli_info_multiline("  These files end up in: funkphp/_internals/compiled/");
            cli_info_multiline("***IMPORTANT 1*** This overwrites the current Troute Files!!!");
            cli_info_multiline("***IMPORTANT 2*** Files are Backed Up in _funkphp/_BACKUPS/compiled/ & _BACKUPS/_FINAL_BACKUPS/!!!");
            exit;
        },
    ],
    'add' => [
        'all_routes' => function () use ($argv, $outPutDir) {},
        'only_route' => function () use ($argv, $outPutDir) {
            if (!isset($argv[3]) || !is_string($argv[3]) || empty($argv[3])) {
                cli_err_syntax("No FunkPHP Command was given?!\nShould be at least three non-empty string arguments!");
            }
            cli_info("Adding route routes (not implemented yet)");
        },
        'only_data_route' => function () use ($argv) {
            if (!isset($argv[3])) {
                cli_err_syntax("No FunkPHP Command was given?!\nShould be at least three arguments!");
            }
            cli_info("Adding data routes (not implemented yet)");
        },
        'only_page_route' => function () use ($argv) {
            if (!isset($argv[3])) {
                cli_err_syntax("No FunkPHP Command was given?!\nShould be at least three arguments!");
            }
            cli_info("Adding page routes (not implemented yet)");
        },
    ],
    'change' => [
        'route' => function () use ($argv) {
            if (!isset($argv[3])) {
                cli_err_syntax("No FunkPHP Command was given?!\nShould be at least three arguments!");
            }
            cli_info("[INFO]: Changing route routes (not implemented yet)");
        },
        'page' => function () use ($argv) {
            if (!isset($argv[3])) {
                cli_err_syntax("No FunkPHP Command was given?!\nShould be at least three arguments!");
            }
            cli_info("[INFO]: Changing page routes (not implemented yet)");
        },
        'data' => function () use ($argv) {
            if (!isset($argv[3])) {
                cli_err_syntax("No FunkPHP Command was given?!\nShould be at least three arguments!");
            }
            cli_info("[INFO]: Changing data routes (not implemented yet)");
        },
    ],
    'delete' => [
        'route_compiled_and_singles' => function () use ($argv) {

            cli_info("[INFO]: Deleting route routes (not implemented yet)");;
        },
        'page' => function () use ($argv) {
            if (!isset($argv[3])) {
                cli_err_syntax("No FunkPHP Command was given?!\nShould be at least three arguments!");
            }
            cli_info("[INFO]: Deleting page routes (not implemented yet)");
        },
        'data' => function () use ($argv) {
            if (!isset($argv[3])) {
                cli_err_syntax("No FunkPHP Command was given?!\nShould be at least three arguments!");
            }
            cli_info("[INFO]: Deleting data routes (not implemented yet)");;
        },
    ],
    'restore' => [
        'route_compiled_and_singles' => function () use ($argv, $dirs, $exactFiles) {
            // Grab backup dir and restore exact file path
            $oldRouteFileDir = $dirs['backups_compiled'];
            $oldSingleRouteFileDir = $dirs['backups_routes'];
            $exactRestorePathTroute = $exactFiles['troute_route'];
            $exactRestorePathSingleRoute = $exactFiles['single_routes'];
            $exactRestorePathSingleMiddlwaresRoute = $exactFiles['single_middlewares'];

            cli_restore_file($oldRouteFileDir, $exactRestorePathTroute, "troute_route");
            cli_restore_file($oldSingleRouteFileDir, $exactRestorePathSingleRoute, "route_single_routes");
            cli_restore_file($oldSingleRouteFileDir, $exactRestorePathSingleMiddlwaresRoute, "route_middleware_routes");
        },
        'data_compiled_and_singles' => function () use ($argv, $dirs, $exactFiles) {

            // Grab backup dir and restore exact file path
            $oldRouteFileDir = $dirs['backups_compiled'];
            $oldSingleRouteFileDir = $dirs['backups_data'];
            $exactRestorePathTroute = $exactFiles['troute_data'];
            $exactRestorePathSingleRoute = $exactFiles['single_data'];
            $exactRestorePathSingleMiddlwaresRoute = $exactFiles['single_middlewares_data'];

            cli_restore_file($oldRouteFileDir, $exactRestorePathTroute, "troute_data");
            cli_restore_file($oldSingleRouteFileDir, $exactRestorePathSingleRoute, "data_single_routes");
            cli_restore_file($oldSingleRouteFileDir, $exactRestorePathSingleMiddlwaresRoute, "data_middleware_routes");
        },
        'page_compiled_and_singles' => function () use ($argv, $dirs, $exactFiles) {

            // Grab backup dir and restore exact file path
            $oldRouteFileDir = $dirs['backups_compiled'];
            $oldSingleRouteFileDir = $dirs['backups_pages'];
            $exactRestorePathTroute = $exactFiles['troute_page'];
            $exactRestorePathSingleRoute = $exactFiles['single_page'];
            $exactRestorePathSingleMiddlwaresRoute = $exactFiles['single_middlewares_page'];

            cli_restore_file($oldRouteFileDir, $exactRestorePathTroute, "troute_page");
            cli_restore_file($oldSingleRouteFileDir, $exactRestorePathSingleRoute, "page_single_routes");
            cli_restore_file($oldSingleRouteFileDir, $exactRestorePathSingleMiddlwaresRoute, "page_middleware_routes");
        },
        'help' => function () {
            cli_info_multiline("FunkCLI - Restore Help");
            cli_info_multiline("Usage: funkcli restore [route_compiled_and_singles|data_compiled_and_singles|page_compiled_and_singles]");
            cli_info_multiline("------------------------------------------");
            cli_info_multiline("The different values:");
            cli_info_multiline("  route_compiled_and_singles - Restores Compiled & Single Route (including Middlewares) routes from backup (earliest version)");
            cli_info_multiline("  data_compiled_and_singles - Restores Compiled & Single Data (including Middlewares) routes from backup (earliest version)");
            cli_info_multiline("  page_compiled_and_singles - Restores Compiled & Single Page (including Middlewares) routes from backup (earliest version)");
            cli_info_multiline("  The Troute files end up in: funkphp/_internals/compiled/");
            cli_info_multiline("  The Single Route (& Middleware) files end up in: funkphp/routes/");
            cli_info_multiline("  The Single Data (& Middleware) files end up in: funkphp/data/");
            cli_info_multiline("  The Single Page (& Middleware) files end up in: funkphp/pages/");
            cli_info_multiline("It uses Backup Paths: 'funkphp/_BACKUPS/compiled/', 'funkphp/_BACKUPS/routes/', 'funkphp/_BACKUPS/data/' & 'funkphp/_BACKUPS/pages/'");
            cli_info_multiline("***IMPORTANT 1*** This overwrites the current Troute, Single & Middleware Files!!!");
            cli_info_multiline("***IMPORTANT 2*** The Same Files In _FINAL_BACKUPS Are NOT Removed After Restoration!!!");
            exit;
        },
    ],

    'help' => function () use ($argv) {
        cli_info_multiline("FunkPHP CLI - Help");
        cli_info_multiline("Usage: funkcli [command] [action] [value]");
        cli_info_multiline("Commands:");
        cli_info_multiline("  compile [all_routes|only_[route|page_route|data_route]] - Compile routes");
        cli_info_multiline("  add [all_routes|only_[route|page_route|data_route]] [value] - Add new routes");
        cli_info_multiline("  change [route|page|data] [oldValue] [newValue]  - Change existing routes");
        cli_info_multiline("  delete [route|page|data] [value] - Delete existing routes");
        exit;
    },
];

// Execute the command with the action if it exists
$command = $argv[1] ?? null;
$action = $argv[2] ?? null;
if (isset($commands[$command]) && $action == null) {
    $commands[$command]();
    exit;
}
if (isset($commands[$command][$action])) {
    $commands[$command][$action]();
    exit;
}

// Catch-all for non-existing commands or actions (or invalid processing of commands)
cli_err_syntax("That FunkCLI Command doesn't exist! Enter ``funkcli help`` for more information!");
exit;
?>